// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'getx_application1';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String GROUP_20 = 'assets/images/Group 20.svg';
  static const String GROUP_21 = 'assets/images/Group 21.svg';
  static const String GROUP_23 = 'assets/images/Group 23.svg';
  static const String GROUP_8 = 'assets/images/Group 8.svg';
  static const String RECTANGLE_18 = 'assets/images/Rectangle 18.svg';
  static const String RECTANGLE_2 = 'assets/images/Rectangle 2.svg';
  static const String RECTANGLE_3 = 'assets/images/Rectangle 3.svg';
  static const String VECTOR = 'assets/images/Vector.svg';
  static const String BRO = 'assets/images/bro.svg';
}
